"""empty message

Revision ID: e260e7610549
Revises: 684522a52880
Create Date: 2021-06-11 16:11:00.243719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e260e7610549'
down_revision = '684522a52880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('parent_artist_id', sa.Integer(), nullable=True))
    op.add_column('Show', sa.Column('parent_venue_id', sa.Integer(), nullable=True))
    # set parent artist and venue temporatly to 4
    op.execute("""UPDATE "Show" SET parent_artist_id = 4 WHERE parent_artist_id IS NULL;""")
    op.execute("""UPDATE "Show" SET parent_venue_id = 4 WHERE parent_venue_id IS NULL;""")
    # set back to nullable=False
    op.alter_column('Show', 'parent_artist_id', nullable=False)
    op.alter_column('Show', 'parent_venue_id', nullable=False)
    op.create_foreign_key(None, 'Show', 'Artist', ['parent_artist_id'], ['id'])
    op.create_foreign_key(None, 'Show', 'Venue', ['parent_venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_column('Show', 'parent_venue_id')
    op.drop_column('Show', 'parent_artist_id')
    # ### end Alembic commands ###
